# Generated by Django 5.2.7 on 2025-10-10 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("universities", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentuniversity",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.studentprofile"
            ),
        ),
        migrations.AddField(
            model_name="universitycampus",
            name="university",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campuses",
                to="universities.university",
            ),
        ),
        migrations.AddField(
            model_name="studentuniversity",
            name="campus",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="universities.universitycampus",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="universitycampus",
            unique_together={("university", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="studentuniversity",
            unique_together={("student", "campus")},
        ),
    ]
