# Generated by Django 5.2.7 on 2025-10-11 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("universities", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="university",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="university",
            name="longitude",
        ),
    ]
