# Generated by Django 5.2.7 on 2025-10-08 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("points", "0001_initial"),
        ("universities", "0001_initial"),
        ("users", "0003_ownerprofile_studentprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="PredefinedService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Accommodation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("accommodation_type", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=255)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("monthly_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("coexistence_rules", models.TextField(blank=True)),
                ("publication_date", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="draft", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accommodations",
                        to="users.ownerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AccommodationPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField()),
                ("order_num", models.IntegerField(default=0)),
                ("is_main", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "accommodation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="accommodations.accommodation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AccommodationNearbyPlace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "distance_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("walking_time_min", models.IntegerField(blank=True, null=True)),
                (
                    "accommodation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nearby_places",
                        to="accommodations.accommodation",
                    ),
                ),
                (
                    "point_of_interest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="near_accommodations",
                        to="points.pointofinterest",
                    ),
                ),
            ],
            options={
                "unique_together": {("accommodation", "point_of_interest")},
            },
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "accommodation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accommodations.accommodation",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.studentprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "accommodation")},
            },
        ),
        migrations.CreateModel(
            name="AccommodationService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("detail", models.CharField(blank=True, max_length=255)),
                (
                    "accommodation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="accommodations.accommodation",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accommodations.predefinedservice",
                    ),
                ),
            ],
            options={
                "unique_together": {("accommodation", "service")},
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.SmallIntegerField()),
                ("comment", models.TextField(blank=True)),
                ("review_date", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="visible", max_length=20)),
                (
                    "accommodation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="accommodations.accommodation",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.studentprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("accommodation", "student")},
            },
        ),
        migrations.CreateModel(
            name="UniversityDistance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("distance_km", models.DecimalField(decimal_places=2, max_digits=6)),
                ("walk_time_minutes", models.IntegerField(blank=True, null=True)),
                ("bus_time_minutes", models.IntegerField(blank=True, null=True)),
                (
                    "accommodation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accommodations.accommodation",
                    ),
                ),
                (
                    "university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="universities.university",
                    ),
                ),
            ],
            options={
                "unique_together": {("accommodation", "university")},
            },
        ),
    ]
