# Generated by Django 5.2.7 on 2025-10-10 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accommodations", "0001_initial"),
        ("points", "0001_initial"),
        ("universities", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accommodation",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accommodations",
                to="users.ownerprofile",
            ),
        ),
        migrations.AddField(
            model_name="accommodationnearbyplace",
            name="accommodation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nearby_places",
                to="accommodations.accommodation",
            ),
        ),
        migrations.AddField(
            model_name="accommodationnearbyplace",
            name="point_of_interest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="near_accommodations",
                to="points.pointofinterest",
            ),
        ),
        migrations.AddField(
            model_name="accommodationphoto",
            name="accommodation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="accommodations.accommodation",
            ),
        ),
        migrations.AddField(
            model_name="accommodationservice",
            name="accommodation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="accommodations.accommodation",
            ),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="status",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accommodations.accommodationstatus",
            ),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="accommodation_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accommodations.accommodationtype",
            ),
        ),
        migrations.AddField(
            model_name="favorite",
            name="accommodation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="accommodations.accommodation",
            ),
        ),
        migrations.AddField(
            model_name="favorite",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.studentprofile"
            ),
        ),
        migrations.AddField(
            model_name="accommodationservice",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="accommodations.predefinedservice",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="accommodation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="accommodations.accommodation",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.studentprofile"
            ),
        ),
        migrations.AddField(
            model_name="universitydistance",
            name="accommodation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="accommodations.accommodation",
            ),
        ),
        migrations.AddField(
            model_name="universitydistance",
            name="campus",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accommodation_distances",
                to="universities.universitycampus",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="accommodationnearbyplace",
            unique_together={("accommodation", "point_of_interest")},
        ),
        migrations.AlterUniqueTogether(
            name="favorite",
            unique_together={("student", "accommodation")},
        ),
        migrations.AlterUniqueTogether(
            name="accommodationservice",
            unique_together={("accommodation", "service")},
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("accommodation", "student")},
        ),
        migrations.AlterUniqueTogether(
            name="universitydistance",
            unique_together={("accommodation", "campus")},
        ),
    ]
