# Generated by Django 5.2.7 on 2025-10-10 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accommodations", "0002_accommodationstatus_accommodationtype_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="predefinedservice",
            name="icon_class",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
