# Generated by Django 5.2.7 on 2025-10-21 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='rooms',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
