# Generated by Django 5.2.7 on 2025-10-10 05:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accommodations", "0003_predefinedservice_icon_class"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accommodationphoto",
            name="image_url",
        ),
        migrations.AddField(
            model_name="accommodationphoto",
            name="image",
            field=cloudinary.models.CloudinaryField(
                default="default.jpg", max_length=255, verbose_name="image"
            ),
            preserve_default=False,
        ),
    ]
