# Generated by Django 5.2.7 on 2025-10-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_ownerprofile_studentprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_owner",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_student",
        ),
        migrations.AddField(
            model_name="user",
            name="roles",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="users.role"
            ),
        ),
    ]
