# Generated by Django 5.2.7 on 2025-10-08 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_userstatus_ownerprofile_status_studentprofile_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="roles",
        ),
        migrations.DeleteModel(
            name="Role",
        ),
    ]
