# Generated by Django 5.2.7 on 2025-10-09 00:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_user_roles_delete_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="avatar_url",
        ),
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="avatar"
            ),
        ),
    ]
